#Data Acquisition

The first step of the machine learning research pipeline is the data acquisition step. Here the following tasks are undertaken:

- Locate data sources
- Load data source
- Check data integrity
- Review data structure
- Preview Data

## Case Study: Malta International Airport

Loading the [Malta International Airport](https://maltairport.com/) passenger movements statistical data in different formats.

In [4]:
# Load Libraries
import pandas as pd
import os.path as osp

# P.S. pd is an alias for pandas library, which allows us to load data in a data frame.
# P.S. osp is an alias for os.path library, which allows us to work with file paths.
# And is used to have and OS agnostic code, which runs on Windows, Linux and MacOS.

In [5]:
df = pd.read_csv(osp.join("..","data", "mia", "miaPassengers 01.csv"))

# We are identifying the data file in an OS agnostic manner using relative positioning, relative to the current file. The .. symbol represents navigating to one folder up (parent folder).
# The osp.join take cares of adding the folder separator based on OS.
# pd is the alias for pandas which loads the csv contents in aa data frame.

# Preview the data structure and do a data integrity check:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

In [10]:
df = pd.read_csv(osp.join('..','data','mia','miaPassengers 02.csv'))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year;passengers  19 non-null     str
dtypes: str(1)
memory usage: 284.0 bytes

In [12]:
df = pd.read_csv(osp.join('..','data','mia','miaPassengers 02.csv'), sep=';')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [6]:
# Preview the start of the data
df.head() # The default value is 5 rows

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [7]:
# preview the end of the data
df.tail() # The default value is 5 rows

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [15]:
# Loading a textfile with a tab as separator
df = pd.read_csv(osp.join('..','data','mia','miaPassengers.txt'), sep='\t')  
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [ ]:
df.tail()

In [16]:
# Load the data from a JSON file
df = pd.read_json(osp.join('..','data','mia','miaPassengers.json'))
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [ ]:
df.tail()

In [18]:
# Accessing a file using file locks to get variable names
with open(osp.join('..','data','mia','miaPassengers.names'), 'r', encoding='utf-8-sig') as f:
    columns = f.read().strip().split(',')

columns

['year', 'passengers']

We created a pointer `f` to the file we want to access and attached a read lock. We also define the encoding, meaning the character space to use to interpret the content, utf8. The `utf-8-sig` variant is needed to support the specific BOM character of this file. Every file ha a BOM and EOF character.

When reading the contents of the file we remove whitespaces using the `strip()` command, then we create a list with the contents of the file using the `split(',')` command since they are comma seperated.

In [19]:
df = pd.read_csv(osp.join('..','data','mia','miaPassengers.data'), names=columns)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [20]:
df.tail()

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [23]:
df= pd.read_excel(osp.join('..','data','mia','miaPassengers.xlsx'))

It appears that `read_excel` is dependent on another package `openpyxl`. Attempting to import that package directly results in an error indicating that it is not installed in out virtual environment.

To install a package in your virtual environment follow these steps:

1. Search for the package on [PyPI](https://pypi.org/)
2. Check the python version compatibility
3. To verify your current python version you can either check the version on your kernel listing in vscode, alternatively in a Terminal/Bash/Command Prompt run `python --version` (for windows) or `python3 --version` (for Linux/Mac)
4. To check the command needed for prior version the page will link in the Previous Versions section
5. Copy the command needed
6. From vscode open a new terminal and make sure the environment is activated
7. Run the command
8. Upon completion in vscode type Ctrl+Shift+P then select `Developer: Reload Window`
9. Re-run the script